import os
import tweepy
from datetime import date, datetime

import time
from image_generation import image_gen
from dotenv import load_dotenv

load_dotenv()
#gets the required keys to use the bot
API_KEY = os.getenv('API_KEY')
API_KEY_SECRET = os.getenv('API_KEY_SECRET')
BEARER_TOKEN = os.getenv('BEARER_TOKEN')
ACCESS_TOKEN = os.getenv('ACCESS_TOKEN')
ACCESS_TOKEN_SECRET = os.getenv('ACCESS_TOKEN_SECRET')

#authorising and loggin in to the account
auth = tweepy.OAuthHandler(API_KEY, API_KEY_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

api = tweepy.API(auth)
#verification of credentials
try:
    api.verify_credentials()
    print("Everything works")
except: 
    print("Something went wrong :(")


# api.update_status("and this one too")
# count = 0
#runs a loop
while True:

    #get the release date of the movie
    d0 = date(2021, 12, 17)
    #get the current date
    d1 = date.today()
    d_test = datetime.now()
    #giving the time for image to get generated and uploaded
    time_to_upload = "14:22"
    #extracting current time (every 60s, because of the sleep function in the bottom)
    extract_time = str(d_test)[11:16]
    # print("time now - " , extract_time)
    #find the number of days between the two days
    delta = d0 - d1
    count = delta.days
    count = str(count)
    time_now = datetime.now().time()
    # print(count)
    api.update_status(extract_time)

    #runs a function that generates and saves the image for that particular day
    
    if time_to_upload == extract_time :
        #takes in the file for that particular day, which was generated by the function above
        file_name = 'assets/images/'+count+'days.png'
        # print(file_name)
        #checks the number of days and sends a tweet accordingly
        
        if int(count) > 1:
            image_gen(count)
            message = count + " more days until 'No Way Home' releases!"
            api.update_with_media(file_name , status = message)

        elif int(count) == 1:
            image_gen(count)
            message = count + " more day until 'No Way Home' releases!!!!!!!!!!!!!!"
            api.update_with_media(file_name , status = message)

        elif int(count) == 0:
            image_gen(count) 
            message = "TODAY IS THE DAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            api.update_with_media(file_name , status = message)
            
            break

        
        #converts count back into integer form
        count = int(count)
    
    time.sleep(60)
