import os
import tweepy
from datetime import date, datetime
import random
import time
from image_generation import image_gen
from dotenv import load_dotenv
template_path_list = ['assets/images/template.png' , 'assets/images/template2.png' , 'assets/images/template3.png']
font_path_list = [ 'assets/fonts/Spiderman-Homecoming.otf' , 'assets/fonts/homoarakhn.regular.ttf' , 'assets/fonts/Amazing Spider Man.ttf']
template_counter = 0
load_dotenv()
#gets the required keys to use the bot
API_KEY = os.getenv('API_KEY')
API_KEY_SECRET = os.getenv('API_KEY_SECRET')
BEARER_TOKEN = os.getenv('BEARER_TOKEN')
ACCESS_TOKEN = os.getenv('ACCESS_TOKEN')
ACCESS_TOKEN_SECRET = os.getenv('ACCESS_TOKEN_SECRET')

#authorising and loggin in to the account
auth = tweepy.OAuthHandler(API_KEY, API_KEY_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

api = tweepy.API(auth)

#verification of credentials
try:
    api.verify_credentials()
    print("Everything works")
    my_id = api.get_user('tangy_31').id
    api.send_direct_message( recipient_id= str(my_id) , text= "bot is up and working!")
    print("message sent!")
except: 
    print("Something went wrong :(")




#runs a loop
while True:
    print("in loop")
    #get the release date of the movie
    d0 = date(2021, 12, 17)
    #get the current date
    d1 = date.today()
    d_test = datetime.now()
    #giving the time for image to get generated and uploaded
    time_to_upload = "06:30"
    #extracting current time (every 60s, because of the sleep function in the bottom)
    extract_time = str(d_test)[11:16]
    #find the number of days between the two days
    delta = d0 - d1
    count = delta.days
    count = str(count)
    time_now = datetime.now().time()
    
    #runs a function that generates and saves the image for that particular day
    
    if time_to_upload == extract_time :
        #takes in the file for that particular day, which was generated by the function above
        file_name = 'assets/images/'+count+'days.png'
        
        #checks the number of days and sends a tweet accordingly
        
        if int(count) > 1:
            image_gen(count , random.choice(template_path_list))
            message = count + " more days until 'No Way Home' releases!"
            api.update_with_media(file_name , status = message)
            api.send_direct_message( recipient_id= str(my_id) , text= "tweet sent!")

        elif int(count) == 1:
            

            image_gen(count ,  random.choice(template_path_list))
            message = count + " more day until 'No Way Home' releases!!!!!!!!!!!!!!"
            api.update_with_media(file_name , status = message)
            api.send_direct_message( recipient_id= str(my_id) , text= "tweet sent!")

        elif int(count) == 0:
            image_gen(count , random.choice(template_path_list))
            message = "TODAY IS THE DAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            api.update_with_media(file_name , status = message)
            api.send_direct_message( recipient_id= str(my_id) , text= "tweet sent!")
            
            break

        
        #converts count back into integer form
        count = int(count)
    
    time.sleep(60)
